import test from 'node:test';
import assert from 'node:assert/strict';
import {parseScenario,IMPORT_EXAMPLES} from '../lib/scenario.mjs';
import {prepareRiverGame} from '../lib/river-engine.mjs';
import {observedPath} from '../lib/observed-path.mjs';
function setup(){const parsed=parseScenario(IMPORT_EXAMPLES[2].text,{street:'river'}),scenario=parsed.scenario;scenario.players[0].range='AhQh,7c7d';scenario.players[1].range='AcKd,9d9s';const result=prepareRiverGame({...scenario,sizes:[100*12/21],allIn:false,raiseSizes:[50],maxRaises:1});return {scenario,result,context:{ledger:parsed.ledger,issues:parsed.issues}};}
test('completed hand opens the actual hero decision before their recorded action',()=>{const {scenario,result,context}=setup(),r=observedPath(scenario,result,context);assert.equal(r.exactMatch,true);assert.equal(r.decisions.length,2);assert.equal(r.pending,null);assert.equal(r.target.actor,1);assert.equal(r.target.recordedAction,'call');assert.deepEqual(r.target.path,['bet_12']);assert.equal(r.target.toCall,12);});
test('unfinished hand opens the pending decision and keeps recorded actions separate',()=>{const {scenario,result,context}=setup();context.ledger=context.ledger.slice(0,context.ledger.findIndex(e=>e.street==='river'&&e.type==='call'));const r=observedPath(scenario,result,context);assert.equal(r.pending.isHero,true);assert.equal(r.target.recordedAction,undefined);assert.deepEqual(r.target.path,['bet_12']);});
test('navigation rejects stale root, stack, action order and absent exact size',()=>{const {scenario,result,context}=setup();assert.throws(()=>observedPath({...scenario,pot:22},result,context),/起点底池/);const bad=structuredClone(scenario);bad.players[0].stack=100;assert.throws(()=>observedPath(bad,result,context),/剩余筹码/);const wrong=structuredClone(context);wrong.ledger.find(e=>e.street==='river'&&e.type==='bet').player='seat3';assert.throws(()=>observedPath(scenario,result,wrong),/行动顺序/);const wrongSize=prepareRiverGame({...scenario,sizes:[50],allIn:false,maxRaises:1});assert.throws(()=>observedPath(scenario,wrongSize,context),/真实尺寸/);});
test('unresolved parser errors cannot become seemingly verified tree navigation',()=>{const {scenario,result,context}=setup();context.issues=[{severity:'error',message:'unresolved'}];assert.throws(()=>observedPath(scenario,result,context),/识别错误/);});
