import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {createProAPI} from '../lib/pro-server.mjs';
import {exportUserData,restoreUserData} from '../lib/backup.mjs';
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'pokerlab-research-api-'));const api=createProAPI({root,json:(res,value,status=200)=>Object.assign(res,{value,status}),body:async req=>req.body??{}});const call=async(route,body)=>{const res={};await api.handler({method:body===undefined?'GET':'POST',body},res,new URL(route,'http://localhost'));return res.value;};t.after(async()=>{await api.shutdown();assert.ok(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(root,{recursive:true,force:true});});return {root,api,call};}
async function completed(h,route){for(let i=0;i<400;i++){const r=await h.call(route);if(!['running','queued','preparing','cancelling','cleanup-required'].includes(r.status))return r;await delay(25);}throw Error('timed out');}
const equity={title:'Saved equity test',board:'Ah Kh Qh Jh Th',engine:'cpu',samples:10000,includeStreetTrail:false,stages:[{id:'open',label:'open',players:[{id:'a',position:'BB',range:'2c2d'},{id:'b',position:'BTN',range:'3c3d'}]}]};
const scenario={title:'Board contrast API',board:'Ks7h2d9c3s',pot:20,toAct:0,hero:'AcKd',heroSeat:0,players:[{id:'a',position:'BB',name:'BB',stack:40,range:'AcKd,AhQh,7c7d,QcJc'},{id:'b',position:'BTN',name:'BTN',stack:40,range:'KhQd,QsQd,7s7d,AcJc'}]};
const settings={sizes:[50],raiseSizes:[50],maxRaises:1,iterations:2000,checkEvery:100,accuracy:.05,engine:'cpu'};
test('equity batch persists full inputs, enforces the compute gate and restores history without certifying imported numbers',async t=>{const h=setup(t),record=await h.call('/api/pro/equity-explorations',equity);assert.equal(record.status,'running');const blocked=await h.call('/api/pro/equity-explorations',equity);assert.match(blocked.error,/已有计算/);const r=await completed(h,'/api/pro/equity-explorations/'+record.id);assert.equal(r.status,'complete');assert.deepEqual(r.result.rows[0].players.map(p=>p.equity),[.5,.5]);assert.equal(r.result.rows[0].exact,true);const backup=exportUserData(h.root),target=setup(t);backup.records['equity-explorations'][0].result.rows[0].players[0].equity=999;restoreUserData(target.root,backup);const restored=await target.call('/api/pro/equity-explorations/'+r.id);assert.equal(restored.status,'restored-unverified');assert.equal(restored.result,undefined);assert.equal(restored.unverifiedResult.rows[0].players[0].equity,999);assert.equal(restored.input.stages[0].players[0].range,'2c2d');});
test('equity cancellation publishes no result and permits a subsequent independent run only after cleanup',async t=>{const h=setup(t),input={...equity,board:'Ks7h2d',includeStreetTrail:true,stages:[{...equity.stages[0],players:[{id:'a',range:'22+,A2s+,K2s+,Q2s+'},{id:'b',range:'22+,A2o+,K2o+'}]}]},r=await h.call('/api/pro/equity-explorations',input);await h.call('/api/pro/equity-explorations/'+r.id+'/cancel',{});const stopped=await completed(h,'/api/pro/equity-explorations/'+r.id);assert.equal(stopped.status,'cancelled');assert.equal(stopped.result,undefined);const second=await h.call('/api/pro/equity-explorations',equity);assert.equal(second.status,'running');assert.equal((await completed(h,'/api/pro/equity-explorations/'+second.id)).status,'complete');});
test('one-card experiments freeze predictions and compare independently solved trees, preserving source identity through backup',async t=>{const h=setup(t);const job=await h.call('/api/pro/solve',{scenario,settings});const a=await completed(h,'/api/pro/jobs/'+job.id);assert.equal(a.status,'complete',a.error);await assert.rejects(h.call('/api/pro/board-contrasts',{sourceJobId:a.id,board:'Ks7h2d9cQc',nodePath:['made-up']}),/路径/);await assert.rejects(h.call('/api/pro/board-contrasts',{sourceJobId:a.id,board:'Ks7h2d9cAc'}),/重复|冲突|同一张牌/);const r=await h.call('/api/pro/board-contrasts',{sourceJobId:a.id,board:'Ks7h2d9cQc',prediction:'先检查同一组合的行动损失，而非只看频率',exposure:'unseen',combo:'AcKd'});assert.equal(r.sourceJobId,a.id);assert.notEqual(r.alternativeJobId,a.id);assert.ok(Date.parse(r.createdAt)<=r.job.startedAt);const b=await completed(h,'/api/pro/board-contrasts/'+r.id);assert.equal(b.status,'complete',b.job.error);const out=await h.call('/api/pro/board-contrasts/'+r.id+'/report',{toleranceBB:.1});assert.equal(out.report.focus.scoreable,true);assert.equal(out.record.prediction,r.prediction);const mechanism=await h.call('/api/pro/board-contrasts/'+r.id+'/mechanism',{combo:'AcKd',toleranceBB:.1});assert.equal(mechanism.mechanism.kind,'board-mechanism');assert.equal(mechanism.mechanism.combo,out.report.focus.combo);assert.ok(mechanism.mechanism.verification.maximumActionEVError<1e-8);assert.ok(out.report.actions.every(x=>Math.abs(x.identityError)<1e-9));const target=setup(t),backup=exportUserData(h.root,{includeResults:true});backup.records['board-contrasts'][0].report={mastery:true};restoreUserData(target.root,backup);const loaded=await target.call('/api/pro/board-contrasts/'+r.id+'/report',{});assert.deepEqual(loaded.report.sourceFingerprints,out.report.sourceFingerprints);assert.equal(loaded.record.report,undefined);assert.equal(loaded.record.prediction,r.prediction);});
