import {normalizeScenario} from './scenario.mjs';

// These are transparent research hypotheses, not imported preflop equilibrium
// ranges or population reads. Every preset remains editable before solving.
const source='PokerLab 原创范围研究；范围与到达权重是教学假设，未声称为真实对手、人口统计或预解 GTO。';
const p=(position,stack,range)=>({id:position.toLowerCase(),name:position,position,stack,range});
const make=(id,title,format,board,pot,players,heroSeat,hero,intent,prediction,oneChange,settings={})=>({id,title,format,source,intent,prediction,oneChange,scenario:normalizeScenario({title,format,board,pot,players,heroSeat,hero,toAct:0,rake:0,assumptions:[source,'金额以 BB 表示；从当前街起点建树，先前弃牌者的底牌信息不进入模型。']}),settings:{sizes:[50,100],raiseSizes:[50],maxRaises:1,iterations:30000,accuracy:.03,checkEvery:250,maxSeconds:180,...settings}});

export const STUDY_LIBRARY=[
 make('online-top-pair-raise','顶对为什么不能只看胜率加注？','online','Ks 7h 2h 9c 3s',40,[p('BB',120,'77,22,99,KQs,KJs,AhQh,AhJh,QhJh,JhTh,Th8h,8h6h,6h5h'),p('BTN',120,'AA,AK,KQs,KJs,99,77,AhQh,AhJh,QhJh')],1,'AcKd','拆开跟注收益、薄价值加注和对手再加注。','先写下哪些较差牌会继续面对加注；不要用对手全部下注范围的权益替代。','把 BB 的 KJs 权重从 100% 改成 25%，预测最受影响的动作。'),
 make('live-three-behind','三人底池：身后玩家改变什么？','live','Ks 7h 2h 9c 3s',40,[p('SB',80,'77,22,AhQh,AhJh'),p('BB',100,'AKs,AKo,99,KhQd,KhQc,AhTh,QhJh'),p('BTN',120,'99,22,KcQd,KdQc,QhJh,JhTh')],1,'AcKd','比较首家下注、你的跟注/加注、BTN 冷跟/冷加注的完整后果。','同一手顶对在单挑和三人中，哪些组合会进入价值区间？','只把 BTN 的暗三条到达权重减半，其余完全不动。',{sizes:[50]}),
 make('online-missed-flush-blocker','错过同花：阻断弃牌是否拖累诈唬？','online','Kh 8h 3c 6s 2d',30,[p('BB',90,'KQ,KJs,88,33,66,AhQh,AhJh,QhJh,JhTh,Th9h,9h7h'),p('BTN',90,'AK,KQ,88,33,AhQh,AhJh,AsQs,AsJs,QhJh,QsJs')],1,'AhQh','比较同等牌力下，不同花色对对手继续范围与弃牌范围的移除。','AhQh 和 AsQs 的行动 EV 差异究竟由哪一组对手牌造成？','只降低 BB 错过同花牌的权重，观察花色排序能否反转。'),
 make('online-completed-flush','同花落地：强牌与坚果优势的区别','online','Kh 8h 3c 6s 2h',30,[p('BB',90,'KQ,KJs,88,33,66,AhQh,AhJh,QhJh,JhTh,Th9h,9h7h'),p('BTN',90,'AK,KQ,88,33,AhQh,AhJh,QhJh,JhTh,AsQd,AcJd')],1,'AhQh','研究坚果同花、较小同花和无同花顶对怎样分配尺寸。','最高摊牌权益的组合是否总选择最大的尺寸？','将对手小同花到达权重减半，保持顶对权重。'),
 make('live-four-way-value','四人河牌：价值门槛与加注后果','live','Qh 9c 6d 3s 2c',32,[p('SB',45,'99,66,AhQd,AdQc'),p('BB',65,'33,22,AsQd,AcQs'),p('CO',80,'Q9s,AhQd,KdQc,JcTc'),p('BTN',90,'QQ,AQs,KQs,JcTc')],3,'AcQc','查看四个范围同时兼容时，顶对与两对的价值门槛。','身后有多少人仍能醒来拿到强牌？先预测谁的下注最克制。','只增加 SB 的顶对组合权重，比较 BTN 的薄价值区间。',{sizes:[50],allIn:false,maxRaises:1,iterations:30000}),
 make('live-short-stack-sidepot','短筹码全下与边池：同一手牌两种收益','live','Ah Jc 8d 5s 2c',36,[p('SB',9,'JJ,88,AcKd,AdQh'),p('BB',80,'55,22,AsKd,AcQd,KhQh'),p('BTN',100,'AA,AJs,AsQd,KhQh')],1,'AsKd','把主池权益、边池竞争和加注资格分开研究。','短筹码玩家全下后，剩下两人的下注应该针对谁的范围？','只把 SB 剩余筹码从 9 改为 30 BB，观察树与价值变化。',{sizes:[50],iterations:30000}),
 make('online-paired-board','公共牌成对：葫芦、三条与诈唬捕手','online','Qh Qc 7d 4s 2c',28,[p('BB',80,'77,44,22,QJs,QTs,AA,KK,99,88,AsJs,AsTs'),p('BTN',80,'AQ,KQ,QJs,77,AA,KK,AsJs,AsTs,JTs')],1,'AcQd','按坚果、次坚果、摊牌牌与空气分层，而不是只数成牌率。','AA 的高摊牌权益能否直接转化为下注收益？','把 BB 的 QTs 去掉，观察 AQ 与 AA 受到的不同影响。'),
 make('online-straight-runout','四连张河牌：直线牌面上的尺寸','online','9h 8c 7d 6s 2c',24,[p('BB',60,'T9s,T8s,T7s,55,99,88,77,98s,87s,A9s,AhKh,AhQh'),p('BTN',60,'JT,T9s,55,99,88,98s,AA,KK,AhQh,AhJh')],1,'JhTh','研究高顺、低顺、两对与一对面对极化尺寸时的响应。','哪些组合同时阻断对手强跟注和诈唬加注？','只减少 BB 的 Tx，比较坚果下注与非坚果防守。'),
 make('online-underpair-bluffcatch','弱对子能否成为更好的抓诈唬牌？','online','Ah Kc 8d 5s 2c',30,[p('BB',75,'AQs,AJs,88,55,22,QJs,QTs,JTs,76s'),p('BTN',75,'AQs,AJs,99,77,66,55,22,QJs,JTs')],1,'7c7d','比较不同抓诈唬组合移除对手价值牌与诈唬的净效应。','77 与 99 的差别应由对手哪些具体组合解释？','只移除 BB 的 76s 诈唬来源，再看 77 排序。'),
 make('live-thin-value','现场宽跟注假设：薄价值有多薄？','live','Kd 9c 5h 3s 2c',22,[p('BB',100,'AK,KQ,KJ,KT,99,55,33,22,98s,97s,AhQh,AhJh'),p('BTN',100,'AK,KQ,KJ,AA,99,55,AhQh,AhJh,QhJh')],1,'AcKs','基线先求解，再锁定对手过宽跟注，比较价值区间变化。','如果对手弱 K 不肯弃牌，谁的价值提高、谁的诈唬受损？','在面对半池下注的节点锁定一类弱 K 更多跟注；保留全树其余优化。'),
 make('online-overbet-polarization','超池尺寸：范围两端与中间怎样分工','online','As 9d 6c 4h 2s',35,[p('BB',120,'AQ,AJ,ATs,99,66,44,22,98s,87s,75s'),p('BTN',120,'AA,AK,AQ,99,66,53s,87s,75s,KQs')],1,'AhAd','比较半池、150% 底池与全下下的价值/诈唬组合分布。','中等 Ax 是否因增加超池选项而全部消失？用整棵树检验。','先去掉超池选项求解，再恢复 150% 尺寸，只比较同一组输入。',{sizes:[50,150]}),
 make('live-donk-threeway','三人率先下注：谁能代表强范围？','live','Jh 8c 5d 4s 2h',30,[p('SB',60,'88,55,44,22,76s,JTs,AhKh,AhQh'),p('BB',90,'JJ,88,J9s,AhJd,KcJd,AhQh'),p('BTN',110,'AA,KK,QQ,AJs,KJs,AhKh,QhTh')],0,'7c6c','让每个玩家都能主动下注，研究位置与坚果组合分布。','率先行动者的坚果优势是否足以支持大范围下注？','只移除 SB 的 76s，保持其余范围，看领先下注怎样改变。',{sizes:[50]}),
 make('online-small-spr','低 SPR：下注、加注与全下合并','online','Qc 8h 4d 3s 2c',70,[p('BB',25,'AA,KK,AQ,KQ,88,44,AsKs,AhKh'),p('BTN',25,'AA,KK,QQ,AQ,88,AsKs,AhKh')],1,'AcQd','识别尺寸被剩余筹码裁剪后，实际行动集合的变化。','在同一剩余筹码下，半池和整池是否真的还是两个不同动作？','只把双方剩余筹码从 25 增到 75 BB，比较顶对承诺程度。'),
 make('live-deep-stack','深筹码河牌：再加注改变价值上限','live','Ac Td 7h 4s 2c',40,[p('BB',240,'ATs,A7s,TT,77,44,22,AQs,AJs,KQs,KJs'),p('BTN',240,'AA,TT,77,ATs,AK,AQ,KQs,KJs')],1,'AsAh','让再加注进入树，观察次坚果怎样保留跟注与过牌。','如果只研究一次加注，会高估哪类强牌的下注价值？','对照 maxRaises=1 与 maxRaises=2，同一范围与尺寸。',{sizes:[50],maxRaises:2,maxSeconds:240}),
 make('online-blocking-nuts','阻断坚果：不是自动诈唬通行证','online','Qh 9h 6c 3h 2s',30,[p('BB',90,'AQ,KQ,99,66,33,AhKh,AhJh,KhJh,JhTh,Th8h,8h7h'),p('BTN',90,'QQ,99,66,AhKh,AhJh,KhJh,AhKd,AhJd,AcKd,AcJd')],1,'AhKd','同为无摊牌价值，比较持 Ah 与不持 Ah 的行动及响应。','Ah 移除了坚果同花，也会移除哪些可能弃牌的牌？','只改变 BB 坚果同花与小同花的相对权重。'),
 make('live-three-paired','三人配对牌面：强抓诈唬牌仍可能脆弱','live','8h 8c Kd 5s 2c',28,[p('SB',70,'55,22,98s,87s,KQs,AhQh'),p('BB',95,'KK,AA,AKs,KQs,98s,AhJh'),p('BTN',110,'A8s,88,KJs,55,QhJh,JhTh')],1,'AcAd','逐一追踪领先下注、跟注后身后再加注带来的范围收缩。','AA 在首家下注后和 BTN 加注后是否仍属于同一类决策？','只降低 BTN 三条的到达权重，研究 AA 跟注和弃牌边界。',{sizes:[50],iterations:100000,algorithm:'dcfr'}),
 make('online-weighted-ranges','到达频率：18 个组合不等于 18 个完整组合','online','Jd 7h 4c 3s 2d',24,[p('BB',70,'77,44,33,22,AJs:0.5,KJs:0.5,QJs:0.5,AhKh:0.25,AhQh:0.25,KhQh:0.25'),p('BTN',70,'AA,KK,QQ,AJ,KJs,77,44,AhKh,AhQh')],1,'AcJh','将原始组合数、权重总和、互相阻断后的到达概率分开。','把所有价值与诈唬权重等比例减半，会改变条件策略吗？','先整体缩放，再只缩放诈唬；比较这两种操作的差异。'),
 make('live-five-way-small','五人底池：受控范围下的联合约束','live','Ah Qc 8d 5s 2c',25,[p('SB',20,'8c8h,AcKd,KhJh'),p('BB',25,'5c5d,AdKs,KdJd'),p('LJ',35,'2d2h,AsKc,KcJc'),p('CO',40,'QdQh,AcJd,KhTh'),p('BTN',50,'AdAs,AcQd,Kh9h')],4,'AcQd','用明确的小范围检验五人共同发牌、行动顺序及弃牌后范围。','人数增加后，为何不能把四个单挑胜率相乘当成联合权益？','移除一位玩家，再比较保留下来的范围兼容权重。',{sizes:[50],allIn:false,maxRaises:0,iterations:30000}),
 make('online-river-checkback','能摊牌的中等牌：保护过牌与薄价值','online','Ts 7c 4h 3d 2c',26,[p('BB',80,'AT,KTs,QTs,77,44,33,22,98s,86s,AhQh,AhJh'),p('BTN',80,'AA,KK,QQ,JJ,AT,KTs,77,44,AhQh,AhJh')],1,'JcJd','比较一对牌的过牌收益和让更差牌付费的机会。','JJ 面对更宽跟注与更多加注时，下注 EV 变化方向是否相同？','分别只增加 BB 的 Tx 和暗三条；不要一次改变两组。'),
 make('live-different-stacks','覆盖关系：我有 200BB，但对手只有 40BB','live','Kh Td 6c 4s 2d',30,[p('SB',40,'TT,66,44,22,KQs,KJs,AhQh'),p('BB',80,'KK,AK,KQs,TT,AhQh,Jh9h'),p('BTN',200,'AA,KT,66,KJs,QhJh,Jh9h')],1,'AcKd','同时理解有效筹码、短码主池和深码之间仍可形成的边池。','所有人的有效筹码能否被一个统一数字替代？','只把 BTN 200BB 改为 80BB，观察哪些分支真正变化。',{sizes:[50]})
];

const turnSettings={sizes:[50],raiseSizes:[50],maxRaises:1,riverSizes:[50],riverRaiseSizes:[50],riverMaxRaises:1,allIn:false,iterations:30000,accuracy:.1,checkEvery:250,maxSeconds:180,maxDeals:1000000,maxNodes:50000};
STUDY_LIBRARY.push(
 make('live-turn-fourway','四人转牌：联合阻断、加注与河牌计划','live','Ks 7h 2h 9c',20,[p('SB',12,'AcKd,AhQh,7c7d,AcKh,KhQd,JhTh'),p('BB',18,'KcQd,QhJh,9h9s,AdKc,AhTh,7d7s'),p('CO',25,'AdKh,AhJh,2c2d,AcKc,Th8h,9d9s'),p('BTN',30,'KdQc,JhTh,7d7s,AsKc,AhTh,2d2s')],0,'AhQh','四人各六个明确组合，完整枚举未来河牌；逐层研究转牌下注、跟注、加注及不等筹码下的河牌计划。','强听牌在四人范围同时兼容时，能否像单挑一样积极进攻？先说清身后继续范围和未来有利河牌。','只降低 BTN 的 7d7s 权重，其余组合、筹码与下注树保持不变。',{...turnSettings,riverMaxRaises:0,iterations:2000}),
 make('online-turn-draws','转牌听牌：权益兑现取决于下一街','online','Ks 7h 2h 9c',24,[p('BB',60,'7c7d,2c2d,KcQd,KdQc,AhJh,QhJh,Th8h,6h5h'),p('BTN',60,'AcKd,AdKc,9d9s,7s7c,AhQh,AhTh,QhTh,JsTs')],1,'AhQh','完整计算转牌及所有合法河牌；对比过牌、下注、加注与未来兑现。','同花听牌的摊牌权益与跟注 EV 为什么不能互相替代？','只降低 BB 暗三条的转牌到达权重，然后重新求解。',turnSettings),
 make('live-turn-threeway','三人转牌：听牌、身后压力与河牌计划','live','Qh Ts 7h 2c',27,[p('SB',70,'7c7d,ThTd,QcJd,QdJc,AhJh,KhJh'),p('BB',95,'2d2s,QcKd,QdKc,Jh9h,8h9h,AcKh'),p('BTN',110,'QdQs,7s7c,AcQd,AdQc,AhKh,Jc9c')],0,'AhJh','三人完整两街模型；让听牌面对跟注、加注、再响应和不同河牌。','若身后玩家拿到强牌，你预计哪些半诈唬组合最先降低进攻频率？','只把 BTN 的两组暗三条权重减半，其他参数保持不变。',{...turnSettings,iterations:5000}),
 make('online-turn-top-pair','顶对的河牌计划：哪些牌改变价值边界？','online','Ad 9h 6c 3s',30,[p('BB',75,'9c9d,6d6s,3c3d,AcQd,AhJd,8c7c,7d5d,KcQc'),p('BTN',75,'AcKh,AhKd,9d9s,AcQh,AhQd,8d7d,KdQd,5c4c')],1,'AcKh','在同一个转牌解内逐张查看河牌，观察顶对的价值与防守转变。','A、K、完成顺子的牌与空白牌，分别改变了谁的有效组合？','只增加 BB 的错过顺听组合到达权重，再比较空白河牌。',turnSettings),
 make('live-turn-short-stack','三人两街边池：短码权益不等于深码计划','live','Ah Jc 8d 5s',30,[p('SB',8,'JhJd,8h8s,AcKd,AdQh'),p('BB',60,'5c5d,AsKd,AcQd,KhQh'),p('BTN',90,'AcAd,AsJs,AsQd,KdQd')],1,'AsKd','从转牌起点分别计算主池、边池及河牌后的深码行动。','短码全下后，深码玩家的额外下注应该针对哪个范围赚钱？','只把 SB 的剩余筹码从 8 提高至 20 BB。',{...turnSettings,allIn:true,riverMaxRaises:0,algorithm:'cfr-plus',iterations:300000}),
 make('online-flop-commitment','双人翻牌三街：浅筹码承诺与等待','online','Ks 7h 2d',10,[p('BB',2,'AcKd,AhQh:0.3'),p('BTN',2,'KhQd,QcJc:0.7')],0,'AcKd','完整显示翻牌、转牌、河牌策略；用于观察浅筹码下过牌与全下的动态变化。','过牌后下一张牌会改变谁的行动？即使河牌还没发，翻牌策略也必须考虑它。','只修改 QcJc 的到达权重，比较翻牌进攻与等待。',{engine:'hu-postflop',sizes:[],raiseSizes:[],maxRaises:0,riverMaxRaises:0,allIn:true,iterations:300,accuracy:.1,maxNodes:100000,outputScope:'full',maxSeconds:180}),
 make('online-flop-range-interaction','双人翻牌三街：顶对、暗三条与后门牌','online','Qs 8h 3d',12,[p('BB',45,'8c8d,3c3h,AcQd,KcQh,AhKh,JhTh'),p('BTN',45,'QcQd,AcAd,AhQd,KdQh,KhJh,Tc9c')],1,'AhQd','三街共同优化翻牌策略；控制导出规模后研究当前街的范围分工。','增加加注选项，哪些组合的下注频率可能改变？先预测，再比较同一抽象下的频率。','只降低 BB 的 JhTh 后门听牌权重，其余参数不动。',{engine:'hu-postflop',sizes:[50],raiseSizes:[50],maxRaises:1,riverMaxRaises:1,allIn:false,iterations:500,accuracy:.5,maxNodes:200000,outputScope:'auto',maxSeconds:180})
);
export const listStudyLibrary=()=>STUDY_LIBRARY.map(x=>structuredClone(x));
export function getStudyPreset(id){const x=STUDY_LIBRARY.find(x=>x.id===id);if(!x)throw Error('研究模板不存在。');return structuredClone(x);}
